char* action[512] =
{
   "No effect",
   "No effect",
   "No effect",
   "Try",
   "Attack",
   "Attack",
   "Spy",
   "Pray",
   "Guard",
   "*Unknown",
   "PSI Special 1",
   "PSI Special 2",
   "PSI Special 3",
   "PSI Special 4",
   "PSI Fire 1",
   "PSI Fire 2",
   "PSI Fire 3",
   "PSI Fire 4",
   "PSI Freeze 1",
   "PSI Freeze 2",
   "PSI Freeze 3",
   "PSI Freeze 4",
   "PSI Thunder 1",
   "PSI Thunder 2",
   "PSI Thunder 3",
   "PSI Thunder 4",
   "PSI Flash 1",
   "PSI Flash 2",
   "PSI Flash 3",
   "PSI Flash 4",
   "PSI Starstorm 1",
   "PSI Starstorm 2",
   "PSI Lifeup 1",
   "PSI Lifeup 2",
   "PSI Lifeup 3",
   "PSI Lifeup 4",
   "PSI Healing 1",
   "PSI Healing 2",
   "PSI Healing 3",
   "PSI Healing 4",
   "Shield 1",
   "Shield 2",
   "Shield 3",
   "Shield 4",
   "PSI Shield 1",
   "PSI Shield 2",
   "PSI Shield 3",
   "PSI Shield 4",
   "PSI Offense up 1",
   "PSI Offense up 2",
   "PSI Defense down 1",
   "PSI Defense down 2",
   "PSI Hypnosis 1",
   "PSI Hypnosis 2",
   "PSI Magnet 1",
   "PSI Magnet 2",
   "PSI Paralysis 1",
   "PSI Paralysis 2",
   "PSI Brainshock 1",
   "PSI Brainshock 2",
   "PSI Teleport 1",
   "PSI Teleport 2",
   "Call for help",
   "Sow seeds",
   "Explode",
   "Burst into flames",
   "Steal an item",
   "Freeze time",
   "Glare with eerie eyes",
   "Generate an electric field",
   "Stumble and fire a beam",
   "Burp and blow breath",
   "Sting with a poison stinger",
   "Give the kiss of death",
   "Exhale arctic-cold breath",
   "Scatter spores",
   "Possess with a mini-ghost",
   "Sprinkle powder",
   "Scatter mold spores",
   "Employ a binding attack",
   "Spit a sticky mucus",
   "Spew Fly Honey",
   "Shoot spider silk",
   "Say something scary",
   "Do something mysterious",
   "Disrupt senses",
   "Size up the situation",
   "Exhale stinky breath",
   "Summon a storm",
   "Spill hot espresso",
   "Play a haunting melody",
   "Extinguising blast",
   "Use Crashing Bang Boom",
   "Shoot a spray of fire",
   "Breath fire",
   "Make something spin around",
   "Lose temper",
   "Say something nasty",
   "Use a vacuum attack",
   "Replenish fuel supply",
   "Bite using poison fangs",
   "Fire a missile, get dizzy",
   "Start a continous attack",
   "Be on guard",
   "Spew a flaming fireball",
   "Rush in and intertwine",
   "Attack with crushing chop",
   "Use a submission hold",
   "Rev and accelerate",
   "Brandish a knife",
   "Tear into",
   "Use a biting attack",
   "Claw with sharp nails",
   "Swing tail very hard",
   "Growl and lunge forward",
   "Wield a shopping bag",
   "Swing a club",
   "Generate a tornado",
   "Generate a blast of water",
   "Flash a menacing smile",
   "Laugh hysterically",
   "Edge closer",
   "Mutter, \"1\"",
   "Murmur, \"2\"",
   "Whisper,\"3\"",
   "Fall down",
   "Be absentminded",
   "Generate steam",
   "Be wobbly",
   "Be reeling",
   "Have a big grin",
   "Take deep breaths",
   "Send a greeting",
   "Make a piercing howl",
   "Say \"tick-tock\"",
   "*Unknown",
   "Restores HP",
   "Restores HP",
   "Restores HP",
   "Restores HP",
   "Hand-Aid",
   "Eat",
   "Recover PP",
   "Recover PP",
   "Restore HP",
   "Defense up 1",
   "Restore HP",
   "Restore HP",
   "*Unknown",
   "Wet Towel",
   "Refreshing herb",
   "Secret herb",
   "Cup of Lifenoodles",
   "used the",
   "IQ up 1",
   "Guts up 1",
   "Speed up 1",
   "Vitality up 1",
   "Luck up 1",
   "Counter-PSI unit",
   "Shield Killer",
   "HP-Sucker",
   "Mummy Wrap",
   "Bottle Rocket",
   "Big Bottle Rocket",
   "Multi Bottle Rocket",
   "Handbag strap",
   "Bomb",
   "Super Bomb",
   "Slime Generator",
   "Yogurt Dispenser",
   "Snake bag",
   "Pair of Dirty socks",
   "Stag Beetle",
   "Toothbrush",
   "Pharaoh's Curse",
   "Hungry HP-Sucker",
   "Bag of Dragonite",
   "Insecticide Spray",
   "Xterminator Spray",
   "Rust promoter",
   "Rust Promoter DX",
   "Sudden guts pill",
   "Defense spray",
   "Defense Shower",
   "Teleport Box",
   "Ruler",
   "Protractor",
   "Pak of Bubble Gum",
   "Fly Honey",
   "Piggy nose",
   "For sale sign",
   "Shyness book",
   "Picture postcard",
   "Secret message",
   "Chick",
   "Chicken",
   "ATM card",
   "Zombie paper",
   "Hawk eye",
   "Bicycle",
   "Emit glorious light",
   "Use electrical shock",
   "Scatter pollen around",
   "Reach out with its hand",
   "Play flute and poison",
   "Spew exhaust fumes",
   "Laugh maniacally",
   "Breath in through flute",
   "Leap and spread wings",
   "Become friendly",
   "Make a loud rumble",
   "Give a great big hug",
   "Hacking cough",
   "Use a misery attack",
   "Utilize paint attack",
   "Come out swinging",
   "Scratch with claws",
   "Peck at eyes",
   "Ram and trample",
   "Throw a punch",
   "Spit pumpkin seeds",
   "Fire a beam",
   "Jab with a spear",
   "Stomp with a huge foot",
   "Swing a hula hoop",
   "Charge forward",
   "Shred fiercely",
   "Bite hard",
   "Grumble about youth",
   "Start lecturing",
   "Scowl sharply",
   "Vent a terrible odor",
   "Shout in a loud voice",
   "Shriek a war cry",
   "Knit a brow",
   "Lose a gear and bolts",
   "Scatter some spores",
   "Use a biting attack",
   "Weapon",
   "Armor",
   "Shoot cold-inducing beam",
   "Coil around and attack",
   "Smoke pour out from body",
   "Poo's special event",
   "Enemy Extender",
   "*Weapon",
   "Neutralizer",
   "*Unknown",
   "Food for one member",
   "Food for all members",
   "Misses home",
   "Body is numb",
   "Fall asleep",
   "Cannot move around",
   "Able to move",
   "Doesn't work very well",
   "Wolf down \"Fly Honey\"",
   "Sound stone",
   "Exit mouse",
   "Pokey-related text",
   "Pokey played dead",
   "Pokey pretended to cry",
   "Pokey apologized profusely",
   "Bark",
   "Chant a magic spell",
   "*Unknown",
   "Scratch head",
   "Snake",
   "Viper",
   "Hieroglyph copy",
   "Town Map",
   "Video Relaxant",
   "Discharge a stinky gas",
   "Cannot grasp true form...",
   "Pokey speech 1",
   "*Unknown",
   "*Unknown",
   "Pokey speech 2",
   "Try to get away",
   "Mirror command",
   "Suporma",
   "Insignificant Item",
   "Monkey's love",
   "Tendakraut",
   "King Banana",
   "Receiver phone",
   "Letter from mom",
   "Letter from Tony",
   "Letter from kids",
   "Give off rainbow of colors",
   "1st prayer",
   "2nd prayer",
   "3rd prayer",
   "4th prayer",
   "5th prayer",
   "6th prayer",
   "7th prayer",
   "8th prayer",                            
   "9th prayer",
   "Giygas damage attack",
   "Giygas feel strange attack",
   "Giygas unknown attack)",
   "Giygas solidify attack)",
   "Giygas crying attack",
   "Giygas unknown attack",
   "3 Giygas attacks",
   "3 Giygas death attacks",
   "Random Giygas quote",
   "2 random Giygas quotes",
   "Bazooka",
   "Heavy Bazooka",
   "<name>",
   "Eat a bologne sandwich",
   "Lose a gear and bolts",
   "Reapply a bandage",
   "Clean the area",
   "Want to get a battery",
   "You can't use the "
};
