char *psinames[100]=   
{
   "PSI Special 1",                         
   "PSI Special 2",
   "PSI Special 3",
   "PSI Special 4",
   "PSI Fire 1",
   "PSI Fire 2",
   "PSI Fire 3",
   "PSI Fire 4",
   "PSI Freeze 1",
   "PSI Freeze 2",
   "PSI Freeze 3",
   "PSI Freeze 4",
   "PSI Thunder 1",
   "PSI Thunder 2",
   "PSI Thunder 3",
   "PSI Thunder 4",
   "PSI Flash 1",
   "PSI Flash 2",
   "PSI Flash 3",
   "PSI Flash 4",
   "PSI Starstorm 1",
   "PSI Starstorm 2",
   "PSI Lifeup 1",
   "PSI Lifeup 2",
   "PSI Lifeup 3",
   "PSI Lifeup 4",
   "PSI Healing 1",
   "PSI Healing 2",
   "PSI Healing 3",
   "PSI Healing 4",
   "Shield 1",
   "Shield 2",
   "Shield 3",
   "Shield 4",
   "PSI Shield 1",
   "PSI Shield 2",
   "PSI Shield 3",
   "PSI Shield 4",
   "PSI Offense up 1",
   "PSI Offense up 2",
   "PSI Defense down 1",
   "PSI Defense down 2",
   "PSI Hypnosis 1",
   "PSI Hypnosis 2",
   "PSI Magnet 1",
   "PSI Paralysis 1",
   "PSI Paralysis 2",
   "PSI Brainshock 1",
   "PSI Brainshock 2",
   "PSI Teleport 1",
   "PSI Teleport 2",  //52
};                    
