char* action[512] =
{
"No effect",
"No effect",
"No effect",
"... tried to use ... But could not use ... very well.",
"Attack",
"Attack",
"Spy",
"Pray",
"Guard",
"(I have no idea)",
"PSI Special 1",
"PSI Special 2",
"PSI Special 3",
"PSI Special 4",
"PSI Fire 1",
"PSI Fire 2",
"PSI Fire 3",
"PSI Fire 4",
"PSI Freeze 1",
"PSI Freeze 2",
"PSI Freeze 3",
"PSI Freeze 4",
"PSI Thunder 1",
"PSI Thunder 2",
"PSI Thunder 3",
"PSI Thunder 4",
"PSI Flash 1",
"PSI Flash 2",
"PSI Flash 3",
"PSI Flash 4",
"PSI Starstorm 1",
"PSI Starstorm 2",
"PSI Lifeup 1",
"PSI Lifeup 2",
"PSI Lifeup 3",
"PSI Lifeup 4",
"PSI Healing 1",
"PSI Healing 2",
"PSI Healing 3",
"PSI Healing 4",
"Shield 1",
"Shield 2",
"Shield 3",
"Shield 4",
"PSI Shield 1",
"PSI Shield 2",
"PSI Shield 3",
"PSI Shield 4",
"PSI Offense up 1",
"PSI Offense up 2",
"PSI Defense down 1",
"PSI Defense down 2",
"PSI Hypnosis 1",
"PSI Hypnosis 2",
"PSI Magnet 1",
"PSI Paralysis 1",
"PSI Paralysis 2",
"PSI Brainshock 1",
"PSI Brainshock 2",
"PSI Teleport 1",
"PSI Teleport 2",
"(some spell)",
"...called for help",
"...sowed some seeds around itself!",
"...exploded into bits!",
"...bursted into flames!",
"...stole a ... in the confusion of the battle!",
"...froze you in time!",
"...glared with its eerie eyes!",
"...generated a mysterious electric field!",
"...stumbled, but fired a strange beam.",
"...burped and blew his nauseating breath at you!",
"...stung you with its poison stinger!",
"...gave ... the kiss of death!",
"...exhaled arctic-cold breath!",
"...scattered some spores!",
"...tried to possess you in a frightening manner.",
"...sprinkled some wonderful-smelling powder.",
"...scattered some mold spores!",
"...employed a binding attack!",
"...spit out a sticky mucus!",
"...spewed Fly Honey out of his mouth!",
"...shot spider silk out of its body!",
"...said something really scary!",
"...did something very mysterious!",
"...disrupted your senses!",
"...is sizing up the situation!",
"...exhaled a blast of stinky breath!",
"...summoned a storm!",
"...spilled some scalding hot espresso!",
"...played a haunting melody!",
"...dispensed an extinguising blast!",
"...used a Crashing Bang Boom attack!",
"...shot out a spray of fire!",
"...breathed fire!",
"...made something spin around!",
"...lost his temper!",
"...said something nasty!",
"...used a vacuum attack!",
"...replenished a fuel supply!",
"...took a bite using its poisonous fangs!",
"...fired a missile, making itself dizzy!",
"...started a continous attack!",
"...is on guard.",
"...spewed out a flaming fireball!",
"...rushed in and intertwined with you!",
"...attacked with a crushing chop!",
"...grappled and used a submission hold!",
"...revved and accelerated!",
"...brandished a knife!",
"...tore into you!",
"...used a biting attack!",
"...clawed ... with sharp nails!",
"...swung its tail very hard!",
"...growled and lunged forward!",
"...wielded a shopping bag!",
"...swung a club!",
"...generated a tornado!",
"...generated a gigantic blast of water!",
"...flashed a menacing smile!",
"...started laughing hysterically!",
"...edged closer!",
"...muttered, \"1...\"",
"...murmured, \"2...\"",
"...whispered, \"3...\"",
"...fell down!",
"...is being absentminded.",
"...generated a burst of steam!",
"...is wobbly.",
"...is reeling.",
"...has a big grin on his face.",
"...is taking deep breaths for the next assault.",
"...sends a greeting!",
"...is making a loud, piercing howl.",
"...is saying \"tick-tock\"",
"135",
"136",
"137",
"138",
"139",
"Hand-Aid effect",
"141",
"142",
"143",
"144",
"145",
"146",
"147",
"148",
"Wet Towel effect",
"Refreshing herb effect",
"Secret herb effect",
"Cup of Lifenoodles effect",
"153",
"154",
"155",
"156",
"157",
"158",
"Counter-PSI unit effect",
"Shield Killer effect",
"HP-Sucker effect",
"Mummy Wrap effect",
"Bottle Rocket effect",
"Big Bottle Rocket effect",
"Multi Bottle Rocket effect",
"Handbag strap effect",
"Bomb effect",
"Super Bomb effect",
"Slime Generator effect",
"Yogurt Dispenser effect",
"Snake bag effect",
"Pair of Dirty socks effect",
"Stag Beetle effect",
"Toothbrush effect",
"Pharaoh's Curse effect",
"Hungry HP-Sucker effect",
"Bag of Dragonite effect",
"Insecticide Spray effect",
"Xterminator Spray effect",
"Rust promoter effect",
"Rust Promoter DX effect",
"Sudden guts pill effect",
"Defense spray effect",
"Defense Shower effect",
"185",
"Ruler effect",
"Protractor effect",
"Pak of Bubble Gum effect",
"Fly Honey effect",
"Piggy nose effect",
"For sale sign effect",
"Shyness book effect",
"Picture postcard effect",
"194",
"Chick effect",
"Chicken effect",
"ATM card effect",
"Zombie paper effect",
"Hawk eye effect",
"Bicycle effect",
"...emitted a glorious light",
"...used an electrical shock attack!",
"...scattered its pollen around!",
"...reached out with its icy hand.",
"...played a flute with its poisonous breath!",
"...spewed exhaust fumes!",
"...started laughing maniacally!",
"...breathed in through its flute!",
"...leaped forward and spread its wings!",
"...became friendly and affectionate!  You backed off!",
"...made a loud rumble!",
"...gave you a great big hug.",
"...let loose with a hacking cough.",
"...used its misery attack!",
"...utilized a paint attack!",
"...came out swinging!",
"...scratched with its claws!",
"...pecked at your eyes!",
"...rammed and trampled you!",
"...threw a punch!",
"...spit its pumpkin seeds!",
"...fired a beam!",
"...jabbed with a spear!",
"...stomped with its huge foot!",
"...swung his hula hoop.",
"...charged forward!",
"...shredded fiercely on a skateboard!",
"...bit you hard!",
"...grumbled about today's youth!",
"...started lecturing you!",
"...scowled sharply!",
"...vented a terrible odor!",
"...shouted in a loud voice!",
"...shrieked a war cry!",
"...knitted its brow!",
"...lost a gear and some bolts!",
"...scattered some spores!",
"...used a biting attack!",
"Weapon",
"Armor",
"...shot a beam that causes night-time stuffiness!",
"...suddenly coiled around you and attacked!",
"Black smoke poured out from ...'s body!",
"...all of a sudden, ... swooped down from the sky!",
"Dunno (ness's nightmare uses it....)",
"Weapon effect or something",
"Neutralizer effect",
"248",
"Food for one person only",
"Food, heals everybody",
"...misses home.",
"...'s body is numb and he can't move!",
"... has fallen asleep!",
"... cannot move around!",
"... was able to move!",
"(some sort of magic that doesn't work very well)",
"... lost his mind by wolfing down \"Fly Honey\"!",
"Sound stone effect",
"Exit mouse effect",
"random battle sentences about Pokey",
"Pokey played dead!",
"Pokey pretended to cry!",
"Pokey apologized profusely!",
"... is barking!",
"... is chanting a magic spell!",
"Dunno",
"... is scratching his head!",
"Snake effect",
"Viper effect",
"Hieroglyph copy effect",
"Town Map effect",
"Video Relaxant effect",
"... discharged a very stinky gas!",
"...<name here>... You cannot grasp the true form of ....'s attack!",
"Pokey's 1st Giygas-related speech",
"Dunno",
"Dunno",
"Pokey's 2nd Giygas-related speech",
"...tried to get away, and did!",
"...relaxed and took a deep breath. (Mirror command)",
"Suporma effect",
"Insignificant Item effect",
"Monkey's love effect",
"Tendakraut effect",
"King Banana effect",
"Receiver phone effect",
"Letter from mom effect",
"Letter from Tony effect",
"Letter from kids effect",
"All of a sudden, ... gave off a rainbow of colors!",
"1st prayer",
"2nd prayer",
"3rd prayer",
"4th prayer",
"5th prayer",
"6th prayer",
"7th prayer",
"8th prayer",
"9th prayer",
"(Random Giygas quote) (damage attack)",
"(Random Giygas quote) (feel strange attack)",
"(Random Giygas quote) (dunno what kind of attack)",
"(Random Giygas quote + damage + solidifying attack)",
"(Random Giygas quote + crying attack)",
"(3 random Giygas quotes + some sort of attack)",
"(3 random Giygas quotes + damage)",
"(3 random Giygas quotes + killer attack)",
"(Random Giygas quote)",
"(2 random Giygas quotes)",
"Bazooka effect",
"Heavy Bazooka effect",
"...<name>...",
"... ate a bologne sandwich!  ...'s HP were maxed out!",
"... lost a gear and some bolts!",
"... reapplied a bandage!",
"... cleaned the area!",
"... wanted to go and get a battery!",
"You can't use the ..."
};
